### ISSUE TITLE
questions while install

### ISSUE THREAD

**Issue by Crypto-zhou** [muqsitnawaz/libfss#1]
I dot know the command "cmake -S .. -B build" should run in which path?I have tried in ./libfss/release/ ,./libfss/src/ and ./libfss/include/ ,then run the following commands,I will always get the same errors,as follows:

<img width="803" alt="Weixin Image_20240526225639" src="https://github.com/muqsitnawaz/libfss/assets/62510564/374093fe-fcb6-48d9-b1b8-d1d25d6c09e9">
 how should i do next?
 
 Good luck to you.
 Thanks

**Comment by yimingqincs** [comment]
I meet the same question . What do you rum this?

**Comment by mialuyao** [comment]
> I meet the same question . What do you rum this?

Have you solved this problem？

**Comment by lwj011** [comment]
Run “cmake -S . -B build” in the root directory (i.e. libfss). The compiled fss_example.cpp can be found in libfss/bin.
